### PR TITLE
Your website on Tailwind

### PR DESCRIPTION
**Pull request by Tyler-Hilbert**
https://tyler-hilbert.github.io/OwenAEdwards.github.io/

### CODE REVIEW

**Comment by Tyler-Hilbert** [comment]
@OwenAEdwards Let me know what you think of the tailwind upgrade

**Comment by OwenAEdwards** [comment]
First, I really appreciate what changes you have put forth by moving my website to Tailwind and I like some of the font changes more than the ones I currently have. I've been meaning to update my website more recently.

That being said, one issue I do have with the Tailwind changes are that my web page is not very responsive to mobile. I.e. the navbar used to navigate the website seems to disappear on mobile, whereas I shrunk my navbar with CSS media queries previously.

I also preferred a darker theme for my website since I pretty much set all my social media websites to dark theme by default to avoid that "flash bang" effect you get from looking at a white web page in a dark room.

The changes you made would also decrease the amount of space being used on each of my three HTML documents (the About Me section, the Experience section, and the Contact Me section). Personally, I wanted to move more towards creating a SPA in order to fill space.

Still, I just want to thank you again for your suggestions and the time you took to make these changes, even though they're not 100% what I want, yet. Thanks again -Owen.

**Comment by Tyler-Hilbert** [comment]
@OwenAEdwards hey that sounds great. Let me know if you know anyone who you think does want a Tailwind upgrade.

**Comment by OwenAEdwards** [comment]
> @OwenAEdwards hey that sounds great. Let me know if you know anyone who you think does want a Tailwind upgrade.

I do actually. I'll send it to you through your UC email👍.

**Pull request closed without merging**
